### ISSUE TITLE
No Wifi Schedule after Off/On of the router

### ISSUE THREAD

**Issue by YvanCB** [newkit/luci-app-wifischedule#1]
Hello,
If I turn On the router in a "Wifi Off" scheduled time, the Wifi is powered and stay On.
My router is a TP-Link Archer C7 v4.
Do you know if there's a solution?
Regards.

**Comment by newkit** [comment]
Sounds like a bug to me ;-) Please be patient, i'll try to look into the issue.

**Comment by YvanCB** [comment]
Hello,

Thank you for you support.
For information I have installed to "**Wifi Toggle**" :https://wiki.openwrt.org/doc/uci/wifitoggle

Regards.

**Comment by YvanCB** [comment]
Hello,

It's me again. Just to tell that I have uninstall "Wifi Toggle" and it's the same problem.

Rgards.

**Comment by YvanCB** [comment]
Hello,
I'm sorry but I would like to know if there is any news about my issue?
Regards.

**Comment by newkit** [comment]
Thank you for you patience. I pushed a new wifi_schedule.sh script that should fix the reported errorneous behaviour. Would you please be so kind and try it out and see if that really fixes your issues? Just copy the wifi_scheduler.sh file to /usr/bin on your router.

**Comment by newkit** [comment]
PS: Here is the fixed script: https://github.com/newkit/wifischedule/blob/master/net/usr/bin/wifi_schedule.sh

**Comment by YvanCB** [comment]
Great!
I will have a look this evening. I'm not fluent with file transfering between PC (under Windows 7) and OpenWrt. I had a look on internet ; I think I can do this with WinSCP...
Thank you for your help and I keep you informed.

Bye...

**Comment by YvanCB** [comment]
Hello,
I have pushed the file "wifi_schedule.sh" in the folder /usr/bin on my router using WinSCP (very easy in fact). I have reboot the router : it seems to be the same thing. I'm in a Off period and the Wifi is On.
What can I do to try to help you to find what's happen?
Thank you very much.

[wifi_schedule.zip](https://github.com/newkit/luci-app-wifischedule/files/2156706/wifi_schedule.zip)

**Comment by newkit** [comment]
:( I had a blind spot there, so I added a startup script.

If you would be so kind to test, please install the latest version of wifi_schedule.sh 
https://github.com/newkit/wifischedule/blob/master/net/usr/bin/wifi_schedule.sh
as before and add the startup script 
https://github.com/newkit/wifischedule/blob/master/net/etc/init.d/wifi_schedule
to /etc/init.d/. 
Make sure it's executable and install it (both commands in an SSH session on the router):
```
chmod +x /etc/init.d/wifi_schedule
/etc/init.d/wifi_schedule enable
```
That should finally disable wifi also when powering on the router if a "wifi off" timewindow.

**Comment by YvanCB** [comment]
Hello,
I have down what you explain to me. I make the file "/etc/init.d/wifi_schedule" executable:
![wifi_schedule propriete](https://user-images.githubusercontent.com/37730353/42233527-20bdfeb8-7ef2-11e8-9f53-a5c72211412e.jpg)

After this I tried to enable it but impossible:
![retour commande](https://user-images.githubusercontent.com/37730353/42233558-34a8360a-7ef2-11e8-88e5-c578f6ce87e3.jpg)

I had reboot my router and enable the script in the router in this menu "http://192.168.1.1/cgi-bin/luci/admin/system/startup" :

![startup](https://user-images.githubusercontent.com/37730353/42233803-d86964a8-7ef2-11e8-8ea1-57d6c808e2c9.jpg)

I will have the result after 8:00 PM. I will inform you as soon as possible.
Regards.

**Comment by YvanCB** [comment]
Hello,
First of all, it's 8:00 PM and the Wifi doesn't turn Off any more :-(.
In startup menu of OpenWRT I have this now:
![startup2](https://user-images.githubusercontent.com/37730353/42237335-c41a24f0-7efd-11e8-9955-cee29e9ee6b1.jpg)
I can put in "enable" but the state return to "Disable" after a refresh screen.
For the moment no more Wifi schedule :-(.
What can I do?

Tank you.

**Comment by newkit** [comment]
Sorry it took me so long to reply. I can only guess what is going wrong on your end, since it's my updated code is not pushed to the upstream repo, yet. Maybe the script is not executed for some reason? It is working here on my router.
Let me open a pull request and once it's in the official build, please feel free to try out again.
Sorry for the inconvenience.
