### ISSUE TITLE
Wifischedule isn't working

### ISSUE THREAD

**Issue by Onoro** [newkit/luci-app-wifischedule#2]
Hello Newkit, thenk you for your software.
I want to ask for help with finding out why wifischedule is not working for me.
It's running on Openwrt 18.04, router's time is correct but it's not turning on and off WiFi by scheduler.

If Wifi interfaces are down (from Luci) and I'm trying to perform commands via console result is:
```

root@TestBox:~# cat /proc/net/wireless | wc -l
2
root@TestBox:~# cat /proc/net/wireless 
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22

```
I even can't disable wifi by pressing button "disable" from wifischeduller uci interface.
And at the same time records in log file are appearing:
Fri Oct 25 07:42:12 EEST 2019 /usr/bin/wifi_schedule.sh start manual
Fri Oct 25 08:19:12 EEST 2019 /usr/bin/wifi_schedule.sh stop manual
Fri Oct 25 08:19:12 EEST 2019 No stations associated, disable wifi.
So log tells me that everything is correct but interfaces are not going up and down via wifischeduler.

How to debug my in my case?

Thanks in advance.

**Comment by newkit** [comment]
Did you detect te modules used by your wifi card and check that they are dtetected properly in the UI?

**Comment by newkit** [comment]
No feedback received, closing.
