### ISSUE TITLE
Update request: restart option

### ISSUE THREAD

**Issue by fauxserve** [newkit/luci-app-wifischedule#3]
I am testing this package to restart wireless on my WAP every night while I'm sleeping. It looks promising. 

I set read the note how if the stop and start times are the same the end result is "off". I am working around that by manually editing the cron jobs to stop, then start one minute later. 
In my quick test it seems to do the job, but the web GUI is out of sync with the cron it sets. 

Could the tool be modified to perform a wifi power cycle natively in the GUI? 
Or save that, provide options to set cron jobs down to the minute/second mark?

**Comment by newkit** [comment]
Hey, 

thanks for your feedback. As far as I understand your use case you want to restart your WIFI every night.
Well, I guess if you are willing to accept a downtime of two minutes that's already possible with the tool, no?
I mean, create a schedule for all days,  that starts WIFI at e.g. 00:01 until 23:59.

Cheers

**Comment by fauxserve** [comment]
I didn't see the "custom" option at the very bottom of the selection window. I'm good! 😆🤦‍♂️
Is two minutes the recommended interval between off/on states? (I have two WAPS, so as long as they are staggered it all should be fine)

**Comment by newkit** [comment]
Happy to help :-D 
Well, I haven't tested the two minutes interval, but my assumption would be that this would be the minimal period to leave some room for the up and down of the IFs.
